\newcommand{\xiv}{\vec{\xi}}
\newcommand{\xv}{\vec{x}}

\newcommand{\argxi}{(\xi_1,\xi_2,\xi_3)}
\newcommand{\argx}{(x_1,x_2,x_3)}

\newcommand{\argxbarn}{(\bar{x}^1,\bar{x}^2,\ldots, \bar{x}^n)}
\newcommand{\argxn}{(x^1, x^2,\ldots, x^n)}

\newcommand{\argxiv}{(\vec{\xi})}
\newcommand{\argxv}{(\vec{x})}

\newcommand{\argtxiv}{(t, \vec{\xi})}
\newcommand{\argtoxiv}{(t_0, \vec{\xi})}

\newcommand{\argtxv}{(t, \vec{x})}
\newcommand{\argtoxv}{(t_0, \vec{x})}

\newcommand{\argtxo}{(t, x)}
\newcommand{\arguv}{(\vec{u})}

\newcommand{\argtxyz}{(t, x, y, z)}
\newcommand{\argtxyztick}{(t', x', y', z')}

\newcommand{\argtxi}{(t, \xi_1,\xi_2,\xi_3)}
\newcommand{\argtoxi}{(t_0, \xi^1,\xi^2,\xi^3)}
\newcommand{\argtx}{(t, x_1,x_2,x_3)}
\newcommand{\argtox}{(t_0, x^1,x^2,x^3)}
\newcommand{\argrz}{(r, z)}

\newcommand{\pd}[2]{\frac{\partial #1}{\partial #2}}
\newcommand{\pdk}[2]{\frac{\partial^2 #1}{\partial {#2}^2}}

\newcommand{\Rho}{\mathscr{P}}
\newcommand{\grad}{\operatorname{grad}}
\newcommand{\rot}{\operatorname{rot}}
\newcommand{\divo}{\operatorname{div}}

\newcommand{\od}[2]{\frac{d #1}{d #2}}
\newcommand{\vard}[2]{\frac{\delta #1}{d #2}}
\newcommand{\odk}[3]{\frac{d^{#3} #1}{d #2^{#3}}}

\renewcommand{\Re}{\operatorname{Re}}
\newcommand{\Sh}{\operatorname{Sh}}
\newcommand{\Eu}{\operatorname{Eu}}
\newcommand{\Fr}{\operatorname{Fr}}

\newcommand{\alert}[1]{\textit{#1}}

\newlist{literature}{enumerate}{1}
\setlist[literature]{partopsep=1pt,label=\arabic{literaturei}.}

\newlist{enum}{enumerate}{1}
\setlist[enum]{partopsep=1pt,label=\arabic{enumi})}

\newlist{problems}{enumerate}{1}
\setlist[problems]{partopsep=1pt,label=\arabic{problemsi}.}


\newtheorem{dfn}{Определение}  
\newtheorem{theorems}{Теорема}  
\newtheorem{problem}{Задача}  

\newcommand{\kg}{\text{кг}}
\newcommand{\m}{\text{м}}
\newcommand{\s}{\text{с}}


